/* Test generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	detach,
	init,
	insert,
	noop,
	safe_not_equal,
	text
} from "/usr/local/lib/node_modules/svelte/internal";

function create_fragment(ctx) {
	let t;

	return {
		c() {
			t = text("/home/jakmeier/fun/gamedev/paddlers/paddlers-frontend/src/game/town/svelte");
		},
		m(target, anchor) {
			insert(target, t, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(t);
		}
	};
}

class Test extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Test;