/* TestComponent generated by Svelte v3.29.0 */
import {
	SvelteElement,
	detach,
	init,
	insert,
	noop,
	safe_not_equal,
	text
} from "/usr/local/lib/node_modules/svelte/internal";

function create_fragment(ctx) {
	let t;

	return {
		c() {
			t = text("/home/jakmeier/fun/gamedev/paddlers/paddlers-frontend/src/game/town/svelte");
			this.c = noop;
		},
		m(target, anchor) {
			insert(target, t, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(t);
		}
	};
}

class TestComponent extends SvelteElement {
	constructor(options) {
		super();
		init(this, { target: this.shadowRoot }, null, create_fragment, safe_not_equal, {});

		if (options) {
			if (options.target) {
				insert(options.target, this, options.anchor);
			}
		}
	}
}

customElements.define("test-component", TestComponent);
export default TestComponent;